# Generated by Django 5.0 on 2023-12-08 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=50)),
                ('constituency', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('result', models.FileField(upload_to='results/')),
                ('fee_statement', models.FileField(upload_to='fee_statements/')),
                ('allocation_status', models.CharField(default='pending', max_length=50)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocation_status', models.CharField(max_length=50)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apply.applicant')),
            ],
        ),
    ]
